CC		?= gcc
CFLAGS		?= -Wall
LDFLAGS		?=
PKG_CONFIG	?= pkg-config

# Debian/Ubuntu-style -l*: works when Allegro headers are on the default include path.
DEFAULT_ALLEG_LIBS := -lallegro -lallegro_main -lallegro_primitives \
	-lallegro_image -lallegro_font -lallegro_audio -lallegro_acodec -lm

# Homebrew/macOS CI: Allegro headers live outside the default path; pkg-config exposes them.
# Build with: make USE_ALLEGRO_PKG_CONFIG=1
ALLEG_PC_MODULES ?= allegro-5 allegro_main-5 allegro_primitives-5 allegro_image-5 \
	allegro_font-5 allegro_audio-5 allegro_acodec-5

ifeq ($(USE_ALLEGRO_PKG_CONFIG),1)
CFLAGS	+= $(shell $(PKG_CONFIG) --cflags $(ALLEG_PC_MODULES))
LDLIBS	:= $(shell $(PKG_CONFIG) --libs $(ALLEG_PC_MODULES)) -lm
else
LDLIBS	:= $(DEFAULT_ALLEG_LIBS)
endif

ICYTOWER_LAN	?= 0
LAN_OBJS	:=

ifeq ($(ICYTOWER_LAN),1)
CFLAGS	+= -DICYTOWER_LAN=1 -Ilan -I.
LAN_OBJS := lan/lan_party.o lan/lan_net.o lan/lan_clock.o lan/lan_msg.o lan/lan_mdns.o
ifeq ($(shell uname -s),Darwin)
CFLAGS	+= -DICYTOWER_HAVE_MDNS=1
LDLIBS	+= -ldns_services
endif
endif

.PHONY: all clean always_check_git_rev lan-probe probe-test

all: icytower

# Phony prerequisite: recipe runs every build. We replace version_gen.h only
# when git output changes (cmp), so menu.o is not recompiled unnecessarily.
version_gen.h: always_check_git_rev
	@set -e; \
	rev=$$(git -C "$(CURDIR)" describe --tags --exact-match HEAD 2>/dev/null) \
		|| rev=$$(git -C "$(CURDIR)" rev-parse --short HEAD 2>/dev/null) \
		|| rev=unknown; \
	{ printf '%s\n' '/* Generated by Makefile - do not edit */'; \
	  printf '#define ICYTOWER_REPO_URL "https://github.com/guysv/icytower"\n'; \
	  printf '#define ICYTOWER_GIT_REV "%s"\n' "$$rev"; } > "$@.tmp"; \
	if test ! -f "$@" || ! cmp -s "$@.tmp" "$@"; then mv "$@.tmp" "$@"; else rm -f "$@.tmp"; fi

always_check_git_rev:

icytower: icytower.o gfx.o sfx.o menu.o options.o characters.o floor_types.o fullscreen.o game.o physics.o highscores.o combo_trail.o third_party/sonic/sonic.o $(LAN_OBJS)

icytower.o: icytower.c icytower.h gfx.h sfx.h menu.h options.h characters.h floor_types.h game.h highscores.h
gfx.o: gfx.c gfx.h
sfx.o: sfx.c sfx.h options.h third_party/sonic/sonic.h
menu.o: menu.c menu.h icytower.h gfx.h sfx.h options.h characters.h floor_types.h fullscreen.h highscores.h version_gen.h
options.o: options.c options.h characters.h floor_types.h
characters.o: characters.c characters.h gfx.h sfx.h
floor_types.o: floor_types.c floor_types.h gfx.h
fullscreen.o: fullscreen.c fullscreen.h
game.o: game.c game.h icytower.h gfx.h sfx.h options.h characters.h floor_types.h physics.h highscores.h combo_trail.h
physics.o: physics.c physics.h
highscores.o: highscores.c highscores.h options.h
combo_trail.o: combo_trail.c combo_trail.h gfx.h options.h physics.h

ifeq ($(ICYTOWER_LAN),1)
lan/lan_party.o: lan/lan_party.c lan/lan_party.h lan/lan_internal.h lan/lan_msg.h lan/lan_mdns.h lan/lan_net.h lan/lan_clock.h icytower.h gfx.h fullscreen.h
lan/lan_net.o: lan/lan_net.c lan/lan_net.h lan/lan_internal.h
lan/lan_clock.o: lan/lan_clock.c lan/lan_clock.h
lan/lan_msg.o: lan/lan_msg.c lan/lan_msg.h lan/lan_internal.h
lan/lan_mdns.o: lan/lan_mdns.c lan/lan_mdns.h lan/lan_internal.h
endif

lan-probe:
	$(MAKE) -C tools/mac_lan_probe

ifeq ($(ICYTOWER_LAN),1)
LAN_TEST_DIR := lan/tests/build

probe-test: $(LAN_TEST_DIR)/lan_loopback_connect
	$(LAN_TEST_DIR)/lan_loopback_connect

$(LAN_TEST_DIR)/lan_loopback_connect: lan/tests/lan_loopback_connect.c lan/lan_msg.c lan/lan_net.c | $(LAN_TEST_DIR)
	$(CC) -Wall -O2 -std=c99 -I. -Ilan -o $@ lan/tests/lan_loopback_connect.c lan/lan_msg.c lan/lan_net.c

$(LAN_TEST_DIR):
	mkdir -p $@

menu.o: lan/lan_party.h
endif

clean:
	rm -f icytower *.o lan/*.o third_party/sonic/*.o version_gen.h
ifeq ($(ICYTOWER_LAN),1)
	rm -rf lan/tests/build
endif
	$(MAKE) -C tools/mac_lan_probe clean 2>/dev/null || true
