CC		?= gcc
CFLAGS		?= -Wall
LDFLAGS		?=
PKG_CONFIG	?= pkg-config

# Debian/Ubuntu-style -l*: works when Allegro headers are on the default include path.
DEFAULT_ALLEG_LIBS := -lallegro -lallegro_main -lallegro_primitives \
	-lallegro_image -lallegro_font -lallegro_audio -lallegro_acodec -lm

# Homebrew/macOS CI: Allegro headers live outside the default path; pkg-config exposes them.
# Build with: make USE_ALLEGRO_PKG_CONFIG=1
ALLEG_PC_MODULES ?= allegro-5 allegro_main-5 allegro_primitives-5 allegro_image-5 \
	allegro_font-5 allegro_audio-5 allegro_acodec-5

ifeq ($(USE_ALLEGRO_PKG_CONFIG),1)
CFLAGS	+= $(shell $(PKG_CONFIG) --cflags $(ALLEG_PC_MODULES))
LDLIBS	:= $(shell $(PKG_CONFIG) --libs $(ALLEG_PC_MODULES)) -lm
else
LDLIBS	:= $(DEFAULT_ALLEG_LIBS)
endif

.PHONY: all clean always_check_git_rev

all: icytower

# Phony prerequisite: recipe runs every build. We replace version_gen.h only
# when git output changes (cmp), so menu.o is not recompiled unnecessarily.
version_gen.h: always_check_git_rev
	@set -e; \
	rev=$$(git -C "$(CURDIR)" describe --tags --exact-match HEAD 2>/dev/null) \
		|| rev=$$(git -C "$(CURDIR)" rev-parse --short HEAD 2>/dev/null) \
		|| rev=unknown; \
	{ printf '%s\n' '/* Generated by Makefile - do not edit */'; \
	  printf '#define ICYTOWER_REPO_URL "https://github.com/guysv/icytower"\n'; \
	  printf '#define ICYTOWER_GIT_REV "%s"\n' "$$rev"; } > "$@.tmp"; \
	if test ! -f "$@" || ! cmp -s "$@.tmp" "$@"; then mv "$@.tmp" "$@"; else rm -f "$@.tmp"; fi

always_check_git_rev:

icytower: icytower.o gfx.o sfx.o menu.o options.o characters.o floor_types.o fullscreen.o game.o physics.o highscores.o combo_trail.o third_party/sonic/sonic.o

icytower.o: icytower.c icytower.h gfx.h sfx.h menu.h options.h characters.h floor_types.h game.h highscores.h
gfx.o: gfx.c gfx.h
sfx.o: sfx.c sfx.h options.h third_party/sonic/sonic.h
menu.o: menu.c menu.h icytower.h gfx.h sfx.h options.h characters.h floor_types.h fullscreen.h highscores.h version_gen.h
options.o: options.c options.h characters.h floor_types.h
characters.o: characters.c characters.h gfx.h sfx.h
floor_types.o: floor_types.c floor_types.h gfx.h
fullscreen.o: fullscreen.c fullscreen.h
game.o: game.c game.h icytower.h gfx.h sfx.h options.h characters.h floor_types.h physics.h highscores.h combo_trail.h
physics.o: physics.c physics.h
highscores.o: highscores.c highscores.h options.h
combo_trail.o: combo_trail.c combo_trail.h gfx.h options.h physics.h

clean:
	rm -f icytower *.o third_party/sonic/*.o version_gen.h
